---
title: Case Study - Beer
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r echo=FALSE, message=FALSE}

library(shiny)
library(ggthemes)
library(dplyr) 
library(tidyverse)
library(forcats)
library(stringr)
library(naniar)
library(corrplot)
library(imputeTS)
library(ggExtra)


beer <- read.csv("./Data/Beers.csv")
brew <- read.csv("./Data/Breweries.csv")

# trimming leading and tailing spaces
brew$State <- str_trim(brew$State,side="both")

## Data Tidying


# left join brew into beer based on brew_id, then renaming and ordering columns
beer_df <- merge(x=beer, y=brew, by.x="Brewery_id", by.y="Brew_ID", all.x=TRUE) %>% 
  plyr::rename(c("Ounces"="Oz", "Brewery_id"="Brewery_ID", "Name.x"="Beer_Name","Name.y"="Brewery_Name"))
 

# reording the columns
beer_df <- beer_df[c(1,8,3,2,9,10,4,5,6,7)]


# trimming leading and tailing spaces
beer_df$State <- str_trim(beer_df$State,side="both")


# get all non NA for ABV and IBU to calculate mean
abv = beer_df[!is.na(beer_df$ABV),]
ibu = beer_df[!is.na(beer_df$IBU),]


# get mean ABV and IBU by style
beer_mean_ABV <<- abv %>% 
  group_by(Style) %>% 
  summarize(mean_ABV = round(mean(ABV),3))

beer_mean_IBU <<- ibu %>% 
  group_by(Style) %>% 
  summarize(mean_IBU = round(mean(IBU),0))


# fill in missing values for IBU where style has no recorded IBU
Style <- c('American Malt Liquor','Braggot','Cider','Flanders Red Ale','Kristalweizen','Low Alcohol Beer','Mead','Rauchbier','Shandy')
mean_IBU <- c(20, 30, 0, 20, 12.5, 15, 1.66, 25, 10.208)
IBU_missing <- data.frame(Style, mean_IBU)
beer_mean_IBU <- rbind(beer_mean_IBU,IBU_missing)


# left join IBU and ABV mean values by style
mean_abv_ibu <- merge(x=beer_mean_ABV, y=beer_mean_IBU, by.x="Style", by.y="Style", all.x=TRUE)


# function to impute mean for ABV and IBU based on means of style
naMeanFill <- function (Style, Column, Colname) {
  if ( Colname == 'ABV') 
    { 
      mean = mean_abv_ibu$mean_ABV[ mean_abv_ibu$Style == Style]
    } 
  else
    { 
      mean = mean_abv_ibu$mean_IBU[ mean_abv_ibu$Style == Style]
    }
  Column[is.na(Column)] <- mean
  return(Column)  
}


# vectorize the function
naMeanFill_v <- Vectorize(naMeanFill)


# fill-in NAs for ABV and IBU
beer_df$ABV <-naMeanFill_v(beer_df$Style,beer_df$ABV,'ABV')
beer_df$IBU <-naMeanFill_v(beer_df$Style,beer_df$IBU,'IBU')
beer_df$IBU <- as.integer(beer_df$IBU)


# imputating NA values with the mean
beer_df_cleaned <- beer_df

ibu    <- beer_df_cleaned$IBU
abv    <- beer_df_cleaned$ABV

statesDF <- distinct(beer_df_cleaned, State)
statesDF$rank <- NA

statesDF$rank[order(statesDF$State)] <- 1:nrow(statesDF)

statesDF <- rbind(statesDF, list("All",0))

statesDF <- statesDF[order(statesDF$rank),]

states <- statesDF$State


library(ggplot2)
library(gridExtra)
library(reshape2)

u <- fluidPage(

  # Application title
  titlePanel("Relationship Between IBU and ABV"),
  
    fluidRow(
    class = "myRow1",
    column(3,
      sliderInput(inputId = "bins", label =  h4("Number of bins:"), min = 1, max = 50, value = 30),

      selectInput("select", label = h4("Histograms or Box Plots"), 
                    choices = list("Histogram" = "hist", "Box Plot" = "box"), 
                    selected = 1),
      
      selectInput("statefilter", label = h4("Filter by State"), 
                    choices = list("States" = states), 
                    selected = 1),
      checkboxInput("lm", label = h4("Add Linear Model"), value = FALSE, width = NULL),
      hr(),
    ),
    
    column(9,
      plotOutput("gmplot")
    ),
    
    tags$head(tags$style(
        "
        .myRow1{height:500px;}
        .shiny-frame{height:650px;}
        "
      )
    ),
    fluid = TRUE
  )
)


s <- shinyServer(function(input, output) 
{
  set.seed(123)


output$gmplot <- renderPlot({

    binsABV <- (max(abv) - min(abv))/input$bins
    binsIBU <- (max(ibu) - min(ibu))/input$bins
    chartype <- input$select
    
    if(input$statefilter == "All"){
      filter <- states
      }
    else {
      filter <- input$statefilter
      }
    
  
    if(chartype == "hist")
    {
        p1 <- beer_df_cleaned %>% filter(State %in% filter) %>% ggplot(aes(ABV)) +  
        geom_histogram(aes(y=..density..), color = "white",fill = "#0e264e", binwidth = binsABV, bins = input$bins) +
        geom_density() +
        labs(x="ABV%", y="Density", title="AVB Distribution")

        p2 <- beer_df_cleaned %>% filter(State %in% filter) %>% ggplot(aes(IBU)) +  
        geom_histogram(aes(y=..density..), color = "white",fill = "#c52551", binwidth = binsIBU, bins = input$bins) +
        geom_density() +
        labs(x="IBU", y="Density", title="IBU Distribution")
        
        
    }

    if(chartype == "box")
    {

        p1 <- beer_df_cleaned %>% filter(State %in% filter) %>% ggplot(aes(y=ABV)) +  
        geom_boxplot(color = "black",fill = "#0e264e", varwidth = TRUE) +
        labs(title="AVB") + 
        theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title.y=element_blank())

        p2 <- beer_df_cleaned %>% filter(State %in% filter) %>% ggplot(aes(y=IBU)) +  
        geom_boxplot(color = "black",fill = "#c52551", varwidth = TRUE) +
        labs(title="IBU") + 
        theme(axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x=element_blank(),
          axis.title.y=element_blank())

    }
    
    if (input$lm == FALSE){
      p3 <- beer_df_cleaned %>% filter(State %in% filter) %>% group_by(State) %>% ggplot(aes(x=ABV, y=IBU)) +
          geom_point() +
          scale_x_continuous("Max ABV (%)",label=scales::percent) + 
          labs(title="Relationship:ABV-IBU")
          # caption="Source: beer, brewery data")
    }
    else {
      p3 <- beer_df_cleaned %>% filter(State %in% filter) %>% group_by(State) %>% ggplot(aes(x=ABV, y=IBU)) +
          geom_point() +
          geom_smooth(method="lm") +
          scale_x_continuous("Max ABV (%)",label=scales::percent) + 
          labs(title="Relationship:ABV-IBU")
      # caption="Source: beer, brewery data")
    }
    
    p4 <- brew %>%
    filter(State %in% filter) %>%
    group_by(State) %>%
    summarise(Breweries = n_distinct(Brew_ID)) %>% 
    mutate(State = fct_reorder(State, desc(Breweries))) %>%
    ggplot(aes(x = State, y = Breweries, fill=State)) + 
    geom_bar(stat="identity") + 
    theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size = 8)) + 
    ggtitle("# of Breweries")
  
    grid.arrange(p1,p2,p3,p4, ncol=2)
  })
})

shinyApp(u,s)

```
